### PR TITLE
Fix backend header set twice

### LINKED ISSUE #60: Error HTTP Headers already set
Recently, @ctmbl noticed in the backend logs this error:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/backend/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/backend/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/backend/node_modules/express/lib/response.js:278:15)
    at getByAuthor (/backend/controllers/articleController.js:23:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### PR DESCRIPTION
**Pull request by atxr**
* Return if error to avoid setting the headers twice
Close #60

### CODE REVIEW

**Review by ctmbl — APPROVED** [review]
Didn't test it but seems quite logic. 
If you tested it right we can merge it :+1:

**Review by amtoine — COMMENTED** [review]
as @ctmbl said, if you tested it, i'm fine with this :relieved: 

### just a question, and i'll approve
what is the new `return` supposed to do? :thinking: 
it only prevents the bug in #60 while keeping the rest of the website intact? :open_mouth:

**Comment by atxr** [comment]
The function `res.status` or `res.sendStatus` can be used only once in a route. It basically sets the response headers.
Here, without this `return`, we set the headers to `404` once and then still execute the remaining code, which will set the headers again at the end.
So this return allows to quit the function when no `author` is provided.

**Review by amtoine — APPROVED** [review]
> The function `res.status` or `res.sendStatus` can be used only once in a route. It basically sets the response headers.
Here, without this `return`, this function might set the headers to `404` once and then still execute the remaining code, which will set the headers again at the end.
So this return allows to quit the function when no `author` is provided. 
>
ok that makes total sense, thanks for the precision :relieved: 

then it's great imo :+1:

**Comment by amtoine** [comment]
again, waiting a bit for @gbrivady :yum: 
@atxr, if you feel time has passed enough, just merge this :wink:

**Comment by atxr** [comment]
Shouldn't we wait for #66 before merging this one?

**Comment by amtoine** [comment]
> Shouldn't we wait for #66 before merging this one?
>
imo, this is a bug fix so, even if it was not planned in the [`0.1.1`](https://github.com/iScsc/iscsc.fr/milestone/3), it still is a bug fix and thus could go inside this patch version ... or after

in the end, that does not look like a big deal at all :wink:

**Review by gbrivady — APPROVED** [review]
Seems fine to me

**Pull request merged**
