### PR TITLE
Remove useless author parameter

### PR DESCRIPTION
**Pull request by atxr**
Remove author parameter in frontend when creating article This parameter is set by the backend during the auth check
This PR needs a test before merging, and I'll wait for the end of #20 to do so.

### CODE REVIEW

**Comment by amtoine** [comment]
Close #21.

**Comment by ctmbl** [comment]
@amtoine I think it does, #21 is linked to this PR

**Comment by atxr** [comment]
Yes exactly!

**Comment by amtoine** [comment]
> @amtoine I think it does, #21 is linked to this PR
>
got it :+1: 

think it was not when i had a look at this PR :open_mouth: 
adding "Close #.." at the end of a PR is a handy feature of _GitHub_ :wink:

**Comment by atxr** [comment]
@amtoine @ctmbl I need your approving to close this now!

**Review by amtoine — APPROVED** [review]
with my basic knowledge of `javascript`, this looks good to me

**Review by ctmbl — APPROVED** [review]

**Pull request merged**
