### PR TITLE
Migrate database to localhost

### PR DESCRIPTION
**Pull request by atxr**
This PR removes the *hardcoded* values of the remote atlas database.
It introduces a new local database deployment in the docker-compose workflow.
The database is secured thanks to docker networking.

I tested the whole migration :heavy_check_mark: 

:warning: This PR doesn't migrate the current atlas db to the new local one. This action must be done "by hand" when the website will be bumped.

### CODE REVIEW

**Review by amtoine — DISMISSED** [review]
this looks good to me even though i've no idea how it works :open_mouth: 

i'll trust you when you say you have tested it => do you think we could test that part of the website during some deployment pipeline?

also, we'll have to wait for `prettier` to work, but that's a detail :relieved:

**Comment by amtoine** [comment]
> **Note**
> once we land #91 and the `prettier` pipeline is fixed, you can
> ```bash
> git fetch iscsc
> git merge iscsc/main
> git push atxr
> ```
> to resolve the conflicts @atxr :+1:

**Comment by atxr** [comment]
> i'll trust you when you say you have tested it => do you think we could test that part of the website during some deployment pipeline?

What do you mean but testing it during some deployment pipeline?

**Comment by amtoine** [comment]
> What do you mean by testing it during some deployment pipeline?
>
well you're saying me you've updated the database, performed local manual tests and that it must 'be done "by hand"' to deploy the website on the server.

i'm wondering if there is some kind of _GitHub_ pipeline we could write to test
- the database is working properly
- the website can be deployed safely

**Comment by atxr** [comment]
Ok yes I see!
Actually we don't have any test to verify that the backend/frontend/database is successfully deployed
But I guess it's a good next step for the CI
The migration of the database from atlas to localhost will be done only once and I'll probably write a little script to do so when we will deploy the website

**Comment by amtoine** [comment]
> Actually we don't have any test to verify that the backend/frontend/database is successfully deployed
But I guess it's a good next step for the CI
>
could you file an issue for this? :yum: 

> The migration of the database from atlas to localhost will be done only once and I'll probably write a little script to do so when we will deploy the website 
>
ok gotcha, no need to spend too much time on that particular migration then :relieved: 
but a general CI that checks the deployment might be great.

**Review by amtoine — APPROVED** [review]
lgtm (CI for the win :triumph:)

**Comment by atxr** [comment]
> could you file an issue for this? yum

Actually no, because we have a bigger plan for the CI with @ctmbl 
We will create an issue soon

**Review by ctmbl — APPROVED** [review]

**Pull request merged**
