### PR TITLE
FEATURE: add `npm run` rule to prettify the code

### PR DESCRIPTION
**Pull request by amtoine**
Related to https://github.com/iScsc/iscsc.fr/pull/96.

this PR adds
- a `pretty` rule in a `Makefile`
- a note in a new PR template about the "_pretty_" error and what to do

> **Note**
> if you have things to change, please edit the PR branch directly, that'll be easier for me, that's just to launch the fix and help contributors :+1:

### CODE REVIEW

**Comment by amtoine** [comment]
i prefer not being assigned to this :wink:

**Review by ctmbl — DISMISSED** [review]

**Comment by ctmbl** [comment]
add to fix the rule due to my experience with #86

**Comment by amtoine** [comment]
@ctmbl 
maybe the CI should be changed then, i think the command should be the same in both files :yum:

**Comment by ctmbl** [comment]
@amtoine it has! in #86 because the real change should have been in #95 or previously but wasn't notified then

**Comment by ctmbl** [comment]
also this is a local problem because this folder I excludes only exists in local, but I changed the CI anyway to homogenize things

**Review by ctmbl — APPROVED** [review]

**Review by ctmbl — APPROVED** [review]
@atxr

**Review by atxr — APPROVED** [review]
Perfect, that will be very handy! :moyai:

**Pull request merged**
